### ISSUE TITLE
As a logged-in user, I want to access my user profile to edit my information.

### ISSUE THREAD

**Issue by dandynstuff** [sopra-fs24-group-24/scrabble-server#11]
**Development Tasks**

- [x] sopra-fs24-group-24/scrabble-server#57
- [x] sopra-fs24-group-24/scrabble-client#20
- [x] sopra-fs24-group-24/scrabble-client#19
- [x] sopra-fs24-group-24/scrabble-client#18
- [x] sopra-fs24-group-24/scrabble-server#61
- [x] sopra-fs24-group-24/scrabble-server#62
- [x] sopra-fs24-group-24/scrabble-client#68

**Acceptance Criteria**

- [x] From the main page, the logged-in user can access their profile to edit personal information and credentials.
- [x] As a logged-in user, they can edit their profile and not other users' profiles.
- [x] After making the wanted changes, the user must click save, and then the changes will take effect
- [x] At any point while editing, the logged-in user can abort editing and go back to the main page.
