### ISSUE TITLE
As a logged-in user, I want to be able to search for other users and friends to see their profile pages

### ISSUE THREAD

**Issue by LucaStephan-Christl** [sopra-fs24-group-24/scrabble-server#12]
**Development Tasks**

- [x] sopra-fs24-group-24/scrabble-client#42
- [x] sopra-fs24-group-24/scrabble-server#105
- [x] sopra-fs24-group-24/scrabble-client#43
- [x] sopra-fs24-group-24/scrabble-client#44

**Acceptance Criteria**

- [x] The user can view a list of registered users displaying username and online status and can be searched with a filter.
- [x] The list of registered users and individual user profiles can only be seen by logged-in users
- [x] The profile page of a user contains the following information: username, online status, friendship status.
- [x] Clicking on a username in the list of registered users redirects to the profile page of the selected user.
