### ISSUE TITLE
As a player, I want to swap my tiles so I have other options to play words.

### ISSUE THREAD

**Issue by LucaStephan-Christl** [sopra-fs24-group-24/scrabble-server#13]
**Development Tasks**

- [x] sopra-fs24-group-24/scrabble-client#17
- [x] sopra-fs24-group-24/scrabble-client#16
- [x] sopra-fs24-group-24/scrabble-client#15
- [x] sopra-fs24-group-24/scrabble-server#54
- [x] sopra-fs24-group-24/scrabble-client#14
- [x] sopra-fs24-group-24/scrabble-server#56

**Acceptance Criteria**

- [x] The player can choose to swap tiles if he/she hasn’t played a word already
- [x] If the player wants to swap tiles, he/she has to select the tiles they want to swap
and confirm them
- [x] If there aren’t enough available tiles to swap, the player is notified and can’t
complete the swap
