### ISSUE TITLE
As a logged-in user, I want to get information about the selected game mode and about my opponents to know how the game mode works and against who I am playing.

### ISSUE THREAD

**Issue by dandynstuff** [sopra-fs24-group-24/scrabble-server#14]
**Development Tasks**

- [x] sopra-fs24-group-24/scrabble-client#13
- [x] sopra-fs24-group-24/scrabble-client#12
- [x] sopra-fs24-group-24/scrabble-server#48
- [x] sopra-fs24-group-24/scrabble-server#49
- [x] sopra-fs24-group-24/scrabble-client#56
- [x] sopra-fs24-group-24/scrabble-client#60
- [x] sopra-fs24-group-24/scrabble-client#61
- [x] sopra-fs24-group-24/scrabble-client#69

**Acceptance Criteria**

- [x] The lobby screen displays the participants (usernames) in the current lobby. As long as the lobby is not full, the logged-in user can leave the lobby by using the button “leave lobby” and confirm it.
- [x] The lobby screen also contains the username of the logged-in user.
- [x] The lobby screen is only visible and accessible for logged-in participants.
- [x] After the lobby is complete, a countdown is started and displayed on each of the participants’ screens and after this, the participants are automatically forwarded to the game which starts.
- [x] As soon as the countdown is started, the button “leave lobby” in the lobby screen gets disabled.
