### ISSUE TITLE
As a logged-in user, I want to either create a new lobby or join an existing lobby to play the game.

### ISSUE THREAD

**Issue by flolanz** [sopra-fs24-group-24/scrabble-server#15]
**Development Tasks**

- [x] sopra-fs24-group-24/scrabble-client#10
- [x] sopra-fs24-group-24/scrabble-client#9
- [x] sopra-fs24-group-24/scrabble-server#38
- [x] sopra-fs24-group-24/scrabble-server#39
- [x] sopra-fs24-group-24/scrabble-server#40
- [x] sopra-fs24-group-24/scrabble-server#41
- [x] sopra-fs24-group-24/scrabble-client#7
- [x] sopra-fs24-group-24/scrabble-server#84
- [x] sopra-fs24-group-24/scrabble-server#90
- [x] sopra-fs24-group-24/scrabble-client#57
- [x] sopra-fs24-group-24/scrabble-client#58
- [x] sopra-fs24-group-24/scrabble-client#59
- [x] sopra-fs24-group-24/scrabble-server#130
- [x] sopra-fs24-group-24/scrabble-client#62
- [x] sopra-fs24-group-24/scrabble-server#152
- [x] sopra-fs24-group-24/scrabble-client#74

**Acceptance Criteria**

- [x] By clicking on one of the listed lobbies, the logged-in user can join the lobby.
- [x] After clicking on “Create a new lobby” the logged-in user can limit the participation to their lobby by making it private with a game pin or to let it open for all registered users.
- [x] The logged-in user should specify the size of the newly created lobby(2-4 players).
- [x] After creating/joining a lobby, the player is navigated to the lobby screen.
