### ISSUE TITLE
As a player, I want to be able to end my turn so I don’t have to wait until the time is up.

### ISSUE THREAD

**Issue by dandynstuff** [sopra-fs24-group-24/scrabble-server#9]
**Development Tasks**

- [x] sopra-fs24-group-24/scrabble-client#23
- [x] sopra-fs24-group-24/scrabble-client#22
- [x] sopra-fs24-group-24/scrabble-client#21
- [x] sopra-fs24-group-24/scrabble-server#66
- [x] sopra-fs24-group-24/scrabble-server#67

**Acceptance Criteria**

- [x] During a player's turn, the turn can always be ended.
- [x] When the player's turn ends, a message is displayed to all players about who's turn is next.
- [x] If a turn ends the game, the end screen is shown.
